- name: Update app_1 version
  set_fact:
    app_1_version: "{{ to_version }}"
    app_2_version: "{{ from_version }}"

- include: update-compose.yml

- name: Mark app_1 as down
  set_fact:
    app_1_down: true

- include: update-nginx-conf.yml

- include: recreate-service.yml app_id=1

- name: Mark app_1 as up
  set_fact:
    app_1_down: false

- name: Mark app_2 as down
  set_fact:
    app_2_down: true

- include: update-nginx-conf.yml

- name: Update app_2 version
  set_fact:
    app_2_version: "{{ to_version }}"

- include: update-compose.yml

- include: recreate-service.yml app_id=2

- name: Mark app_2 as up
  set_fact:
    app_2_down: false

- include: update-nginx-conf.yml
